# Generated by Django 3.2.4 on 2021-07-04 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_carrito_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='estado',
        ),
    ]
