# Generated by Django 3.2.4 on 2021-07-05 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_carrito_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='productos',
            field=models.ManyToManyField(blank=True, to='core.producto'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
